version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: learning
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
