version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: learning
      MYSQL_USER: xavi
      MYSQL_PASSWORD: xavi
    ports:
      - "3306:3306"

#Añadir servicio propio